language: php

php: 7.1

addons:
  rethinkdb: "2.3"

cache:
  directories:
    - /home/travis/build/RoySegall/mini-social/server/vendor


script:
  - cd server
  - composer install --dev
  - php console.php social:install
  - bash tests.sh
