'friends/show/all': '\Social\Controller\AllFriends'
'friends/show/birthdates/previous': '\Social\Controller\ShowPreviousBirthdates'
'friends/show/potentials': '\Social\Controller\ShowPotentials'
'friends/show/birthdays/upcoming': '\Social\Controller\ShowPreviousUpcoming'
